#spring:
#  config:
#    activate:
#      on-profile: secret

secret:
  account:
    admin:
      username: admin
      password: admin
  address:
    cam:
      api: http://localhost:8081
      nginx: http://localhost:8082
