version: "3.9"
services:
  clover-chat-server:
    image: ghcr.io/asdsad/clover-chat-server:latest
    container_name: clover-chat-server
    working_dir: /usr/src/app
    entrypoint: java -jar ./build/libs/clover-chat-server-0.0.1-SNAPSHOT.jar
    environment:
      spring.profiles.active: prod
    ports:
      - "11730:11730"
