FROM bitnami/git:2.45.2 as git
WORKDIR /app
RUN git clone https://github.com/rwiv/smart-cctv-front.git gui
RUN git clone https://github.com/rwiv/smart-cctv.git server

# gui build
FROM node:21.7-alpine as nodejs
COPY --from=git /app/gui /app/gui
WORKDIR /app/gui
RUN npm i
RUN npm run build:prod

# spring build
FROM arm64v8/gradle:8.8-jdk21-alpine as grapdle
COPY --from=git /app/server /app/server
COPY --from=nodejs /app/gui/dist /app/server/src/main/resources/dist
WORKDIR /app/server
RUN gradle build -x check --parallel

# main
FROM arm64v8/openjdk:23-jdk-slim
WORKDIR /app
COPY --from=grapdle /app/server/build/libs/smart-cctv-0.0.1-SNAPSHOT.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]